#!/bin/bash
dir=~/workspace


if [[ ! -e $dir ]]; then
    mkdir $dir
elif [[ ! -d $dir ]]; then
    echo "$dir already exists but is not a directory" 1>&2
fi

docker run -ti --rm \
	--cap-add=SYS_PTRACE \
	-e DISPLAY=$DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /home/$USER:/home/developer/home \
	-v $dir:/home/developer/workspace -e USER=$USER  -e USERID=$UID \
	snyg/eclipse-cdt
